/**
 * iOS PWA splash screens ("startup images").
 *
 * Safari has no manifest-driven splash screen, so every device size needs its own
 * pre-rendered image plus a media query. Images are generated by
 * `npm run generate:splash` into /public/splash.
 */

export const SPLASH_BACKGROUND = "#222224" // matches the logo's own background so it blends seamlessly

/** Portrait CSS pixel dimensions + device pixel ratio for each supported device. */
export const APPLE_SPLASH_DEVICES = [
  // iPhone
  { width: 440, height: 956, ratio: 3 }, // 16 Pro Max
  { width: 430, height: 932, ratio: 3 }, // 14/15/16 Pro Max, 15/16 Plus
  { width: 428, height: 926, ratio: 3 }, // 12/13 Pro Max
  { width: 414, height: 896, ratio: 3 }, // XS Max, 11 Pro Max
  { width: 414, height: 896, ratio: 2 }, // XR, 11
  { width: 414, height: 736, ratio: 3 }, // 8 Plus
  { width: 402, height: 874, ratio: 3 }, // 16 Pro
  { width: 393, height: 852, ratio: 3 }, // 14 Pro, 15, 16
  { width: 390, height: 844, ratio: 3 }, // 12/13/14
  { width: 375, height: 812, ratio: 3 }, // X, XS, 11 Pro, 12/13 mini
  { width: 375, height: 667, ratio: 2 }, // 8, SE 2/3
  { width: 320, height: 568, ratio: 2 }, // SE 1
  // iPad
  { width: 1032, height: 1376, ratio: 2 }, // Pro 13"
  { width: 1024, height: 1366, ratio: 2 }, // Pro 12.9"
  { width: 834, height: 1210, ratio: 2 }, // Pro 11" (M4)
  { width: 834, height: 1194, ratio: 2 }, // Pro 11"
  { width: 834, height: 1112, ratio: 2 }, // Pro 10.5"
  { width: 820, height: 1180, ratio: 2 }, // Air 10.9"
  { width: 810, height: 1080, ratio: 2 }, // 10.2"
  { width: 768, height: 1024, ratio: 2 }, // 9.7", mini 5
  { width: 744, height: 1133, ratio: 2 }, // mini 6
] as const

export type AppleSplashImage = {
  url: string
  media: string
  /** Pixel dimensions of the generated image. */
  pixels: { width: number; height: number }
}

export const APPLE_SPLASH_IMAGES: AppleSplashImage[] =
  APPLE_SPLASH_DEVICES.flatMap(({ width, height, ratio }) => {
    const px = width * ratio
    const py = height * ratio
    const device = `screen and (device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${ratio})`
    return [
      {
        url: `/splash/apple-splash-${px}-${py}.png`,
        media: `${device} and (orientation: portrait)`,
        pixels: { width: px, height: py },
      },
      {
        url: `/splash/apple-splash-${py}-${px}.png`,
        media: `${device} and (orientation: landscape)`,
        pixels: { width: py, height: px },
      },
    ]
  })
